name: Release

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always
  PKG_CONFIG_ALLOW_CROSS: 1

jobs:
  build-crate:
    name: Build Crate
    runs-on: ubuntu-20.04
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.rustup
          target
        key: ${{ runner.os }}-stable
    - name: Setup
      run: |
        rustup install stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test
    # - name: Publish
    #   run: cargo publish
    #   env:
    #     CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish-to-github:
    name: Publish to Github
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
        - build: linux
          os: ubuntu-latest
          rust: stable
          target: x86_64-unknown-linux-gnu
          linker: x86_64-linux-gnu
          cross: false
        - build: arm-v7
          os: ubuntu-latest
          rust: stable
          target: armv7-unknown-linux-gnueabihf
          linker: gcc-arm-linux-gnueabihf
          cross: true
        # - build: aarch64
        #   os: ubuntu-latest
        #   rust: stable
        #   target: aarch64-unknown-linux-gnu
        #   linker: gcc-aarch64-linux-gnu
        #   cross: true
        # - build: macos
        #   os: macos-latest
        #   rust: stable
        #   target: x86_64-apple-darwin
        #   cross: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.rustup
          target
        key: ${{ runner.os }}-${{ matrix.rust }}

    - name: Install Linker
      if: matrix.cross
      run: |
        sudo apt update
        sudo apt install ${{ matrix.linker }}

    - name: Install Ubuntu deps
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install libssl-dev pkg-config
        echo "PKG_CONFIG_PATH=/usr/lib/${{ matrix.linker }}/pkgconfig" >> $GITHUB_ENV
        echo "PKG_CONFIG_LIBDIR=/usr/lib/${{ matrix.linker }}/pkgconfig" >> $GITHUB_ENV
        ls -lah /usr/lib/
      # # On Ubuntu
      # sudo apt-get install libssl-dev
      # # On Arch Linux
      # sudo pacman -S openssl
      # # On Fedora
      # sudo dnf install openssl-devel
      # # On Alpine Linux
      # apk add openssl-dev

    - name: Install Rust
      run: |
        rustup install ${{ matrix.rust }}
        rustup target add ${{ matrix.target }}
        rustup show

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}

    - name: Package Artifacts
      run: |
        src=$(pwd)
        stage=
        case $RUNNER_OS in
            Linux)
                stage=$(mktemp -d)
                ;;
            macOS)
                stage=$(mktemp -d -t tmp)
                ;;
        esac

        cp target/${{ matrix.target }}/release/rpi_admin $stage/
        cd $stage

        RELEASE_VERSION=${GITHUB_REF#refs/tags/}
        ASSET_NAME="rpi-admin-$RELEASE_VERSION-${{ matrix.target }}.tar.gz"
        ASSET_PATH="$src/$ASSET_NAME"
        CHECKSUM_PATH="$ASSET_PATH.sha256"

        echo "ASSET_PATH=$ASSET_PATH" >> $GITHUB_ENV
        echo "CHECKSUM_PATH=$CHECKSUM_PATH" >> $GITHUB_ENV

        tar czf $ASSET_PATH *

        cd $src

        case $RUNNER_OS in
            Linux)
                sha256sum $ASSET_NAME > $CHECKSUM_PATH
                ;;
            macOS)
                shasum -a 256 $ASSET_NAME > $CHECKSUM_PATH
                ;;
        esac


    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{ env.ASSET_PATH }}
          ${{ env.CHECKSUM_PATH }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
